### ISSUE TITLE
The Demo video (animation) on asciinema is broken: 404 Not Found

### ISSUE THREAD

**Issue by za** [python/cherry-picker#64]
Hi there, 

On https://github.com/python/cherry-picker#demo The installation demo video is broken: 404 Not Found. Maybe we can update/delete the link.

https://asciinema.org/a/125254

![Screenshot from 2022-05-27 14-10-58](https://user-images.githubusercontent.com/409455/170650289-ffea9d55-55a3-4873-881e-4e28a005f872.png)

**Comment by ezio-melotti** [comment]
There are two links in the readme:

> - Installation: https://asciinema.org/a/125254
> - Backport: https://asciinema.org/a/125256

The second one still works, but the first is broken.

There are more videos on [@Mariatta's asciinema profile](https://asciinema.org/~Mariatta), including [an "installation" video](https://asciinema.org/a/122933) with a different id.  This is probably older though since it installs cherry-picker from the repo instead of using pypi.

@Mariatta, can you check what happened to the original video?

**Comment by za** [comment]
@ezio-melotti maybe I'll just remove the video link first, until @Mariatta confirmed the updated video.

**Comment by za** [comment]
@Mariatta The URL is accessible now. I'm closing the issue now. Thanks.
